#ifndef UNTITLED_PROGRAMMINGALGORITHMS_DES_H
#define UNTITLED_PROGRAMMINGALGORITHMS_DES_H

void programmingalrorithms_des(uint8_t * text, uint8_t* out);

#endif //UNTITLED_PROGRAMMINGALGORITHMS_DES_H
